version: 2
builds:
  - main: ./cmd/lazytrack
    binary: lazytrack
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: traffiqq
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/traffiqq/lazyTrack"
    description: "Terminal UI for managing YouTrack issues, inspired by lazygit"
    license: "MIT"
    install: |
      bin.install "lazytrack"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
